# Generated by Django 4.2.1 on 2023-07-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznacheistvo_site', '0007_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
