# Generated by Django 4.2.1 on 2023-07-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaznacheistvo_site', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
