# Generated by Django 4.2.1 on 2023-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznacheistvo_site', '0011_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimages',
            name='newsObject',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.RenameField(
            model_name='newsdetails',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='newsdetails',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='NewsImages',
        ),
    ]
