# Generated by Django 4.2.1 on 2023-07-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznacheistvo_site', '0012_remove_newsimages_newsobject_delete_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetails',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
